name: Build Prod APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false

      - name: Run init.sh
        run: |
          chmod +x ./init.sh
          chmod +x ./build.sh
          ./init.sh

      - name: Fix flutter_avif
        run: |
          KT_FILE=$(find $HOME/.pub-cache/hosted/pub.dev -name "FlutterAvifPlugin.kt" | head -1)
          PROPS_FILE=$(find $HOME/.pub-cache/hosted/pub.dev -path "*/flutter_avif_android-*/android/gradle.properties" | head -1)
          cp FlutterAvifPlugin.kt "$KT_FILE"
          echo "" >> "$PROPS_FILE"
          echo "kotlin.jvm.target.validation.mode=IGNORE" >> "$PROPS_FILE"
          cat "$KT_FILE"

      - name: Fix project JVM target
        run: |
          echo "" >> android/gradle.properties
          echo "kotlin.jvm.target.validation.mode=IGNORE" >> android/gradle.properties

      - name: Build Prod FOSS APK
        run: ./build.sh apk --flavor prod --foss

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: boorusama-prod-foss-apk
          path: build/app/outputs/flutter-apk/*-prod*.apk
